# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Register as services
    Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor:
    Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor:



    app.payment_processor.paypal:
        class: App\Payment\Adapters\StripePaymentProcessorAdapterProcessor
        arguments:
            $processor: '@Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor'

    app.payment_processor.stripe:
        class: App\Payment\Adapters\PayPalPaymentProcessorAdapterProcessor
        arguments:
            $processor: '@Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor'

    app.payment_processor_factory:
        class: App\Payment\PaymentProcessorFactory
        arguments:
            - '@app.payment_processor.paypal'
            - '@app.payment_processor.stripe'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
